---
Relations:

  - Customer:
      columns: [id: Int, first_name: String, last_name: String, tier_id: Int, created_date: Date]
      queries: [all-all, byone-customer_id]
  - Message:
      columns: [id: Int, customer_id: Int, body: String, inout: Int, message_type_id: Int, created_date: Date]
      queries: [all-all, by-pk]
  - Toy: 
      columns: [id: String, name: String]   
      queries: [all-all, all-product_version_id]
  - Movie:
      columns: [id: Int, name: String]   
      queries: [all-all, all-product_version_id]

 

                   
Associations:
  - Customer: [ hasMany: Message ]
  - Message: [ belongsTo: Customer ]
  
