apiVersion: apps/v1
kind: Deployment
metadata:
  name: willow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: willow
  template:
    metadata:
      labels:
        app: willow
    spec:
      containers:
        - name: willow
          image: willow/schema
          command:
            - sleep
            - infinity
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: postgres-config
